"""0.1.0

迁移 ID: 5fb8a9a9cc7f
父迁移:
创建时间: 2024-03-03 19:25:35.837080

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "5fb8a9a9cc7f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("kv",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("kv", sa.Column("key", sa.VARCHAR, primary_key=True), sa.Column("value", sa.VARCHAR, nullable=False))
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kv")
    # ### end Alembic commands ###
